name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract
      run: tar -xvzf ngrok.tgz

    - name: Auth
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: sudo apt update && sudo apt upgrade -y
      
    - name: Installing dependencies
      run: sudo apt install xfce4 xfce4-terminal dbus-x11 tigervnc-standalone-server wget x11vnc -y

    - name: Setting up VNC password
      run: x11vnc -storepasswd 13467913 $HOME/.vnc/passwd
      
    - name: Starting VNC server
      run: x11vnc -rfbauth $HOME/.vnc/passwd -display :0 -forever -shared -nopw -geometry 2370x1080
  

    - name: Create Tunnel
      run: ./ngrok tcp 5901
