name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract
      run: tar -xvzf ngrok.tgz

    - name: Auth
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: Installing dependencies
      run: sudo apt install tigervnc-standalone-server wget x11vnc -y

    - name: Setup the necessary files
      run: mkdir -p ~/.vnc
    - name: xstartup
      run: wget https://raw.githubusercontent.com/aloneunknown360/files/main/xstartup -P ~/.vnc/
    - name: setting up
      run: echo "vncserver -geometry 2370x1080 -localhost no" > /usr/local/bin/vnc-start
    - run: echo "vncserver -kill :*" > /usr/local/bin/vnc-stop
    - run: chmod +x ~/.vnc/xstartup
    - run: chmod +x /usr/local/bin/vnc-*
    - run: wget https://raw.githubusercontent.com/aloneunknown360/files/main/passwd -P ~/.vnc/
    - run: echo -e "13467913\n13467913\nn" | vnc-start
    - name: Create Tunnel
      run: ./ngrok tcp 5901
