name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract
      run: tar -xvzf ngrok.tgz

    - name: Auth
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: sudo apt update && sudo apt upgrade -y
      
    - name: Installing dependencies
      run: sudo apt install xfce4 xfce4-terminal dbus-x11 tigervnc-standalone-server wget x11vnc -y

    - name: Setup the necessary files
      run: mkdir -p ~/.vnc && echo "#!/bin/base\n xrdb $HOME/.Xresources\n startxfce4" > ~/.vnc/xstartup
    - name: setting up
      run: echo "vncserver -geometry 1600x900 -name remote-desktop :1" > /usr/local/bin/vnc-start
    - run: echo "vncserver -kill :*" > /usr/local/bin/vnc-stop
    - run: chmod +x ~/.vnc/xstartup
    - run: chmod +x /usr/local/bin/*
    - run: 
    - run: vnc-startwget https://raw.githubusercontent.com/wahasa/Ubuntu/main/Patch/passwd -P .vnc/

    - name: Create Tunnel
      run: ./ngrok tcp 5901
