name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract
      run: tar -xvzf ngrok.tgz

    - name: Auth
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: change directory
      run: cd /

    - name: updating
      run: sudo apt update && sudo apt upgrade -y
        
    - name: Installing dependencies
      run: sudo apt install xfce4 tigervnc-standalone-server wget -y

    - name: getting xstartup
      run: wget https://raw.githubusercontent.com/aloneunknown360/files/main/xstartup -P ~/.vnc/

    - name: Setup the necessary files
      run: mkdir -p ~/.vnc
      
    - name: setting up
      run: echo "vncserver -geometry 2370x1080 -localhost no" > /usr/local/bin/vnc-start
    - run: echo "vncserver -kill :*" > /usr/local/bin/vnc-stop
    - run: chmod +x /usr/local/bin/vnc-*
    - run: wget https://raw.githubusercontent.com/aloneunknown360/files/main/passwd -P ~/.vnc/
    - run: echo -e "13467913\n13467913\nn" | vnc-start
    - name: Create Tunnel
      run: NGROK_URL=$(./ngrok tcp 5901 --log=stdout | grep "URL" | awk -F\" '{print $4}') && echo "Server started: $NGROK_URL"

