name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract
      run: tar -xvzf ngrok.tgz

    - name: Auth
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: sudo apt update && sudo apt upgrade -y
      
    - name: Installing dependencies
      run: sudo apt install xfce4 xfce4-terminal dbus-x11 tigervnc-standalone-server wget -y

    - name: Setting up VNC password
      run: wget https://raw.githubusercontent.com/aloneunknown360/files/main/passwd -P ~/.vnc/

    - name: Starting VNC server
      run: vncserver -geometry 2370x1080 -localhost no


    - name: Create Tunnel
      run: ./ngrok tcp 5901
