name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract
      run: tar -xvzf ngrok.tgz

    - name: Auth
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: sudo apt update && sudo apt upgrade -y
      
    - name: Installing dependencies
      run: sudo apt install xfce4 xfce4-terminal dbus-x11 tigervnc-standalone-server -y

    - name: Setting up VNC passwd
      run: |
        sudo apt-get update
        sudo apt-get install -y expect
        echo '#!/usr/bin/expect -f
        set password "13467913"
        spawn vncpasswd
        expect "Password:"
        send "$password\r"
        expect "Verify:"
        send "$password\r"
        expect eof' > $HOME/vncpasswd_expect.sh
        chmod +x $HOME/vncpasswd_expect.sh
        $HOME/vncpasswd_expect.sh


    - name: Starting VNC server
      run: vncserver -geometry 2370x1080 -localhost no

    - name: Create Tunnel
      run: ./ngrok tcp 5901
